-- Diagnóstico: nota NUMNOTA=290801 (cliente CODPARC=2572) aparece com Créditos Aplicados = 12,10
-- no Relatorio Semanal_fechamento.jrxml, mas o financeiro confirmou que essa nota NÃO teve abatimento.
-- Rode isto direto no banco (sem agrupar) e veja qual Opção do DEV_INFO está gerando esse falso positivo.

DECLARE @NUNOTA_ORIG INT = (
    SELECT TOP 1 NUNOTA
    FROM TGFCAB
    WHERE NUMNOTA = 290801
      AND CODPARC = 2572
      AND TIPMOV <> 'D'
);

SELECT @NUNOTA_ORIG AS NUNOTA_RESOLVIDO;

SELECT
    'Opção 1 (NUCOMPENS)' AS ORIGEM_OPCAO,
    FIN_COMP.NUNOTA AS NUNOTA_ORIG,
    FIN_COMP.NUFIN  AS NUFIN_COMP,
    FIN_COMP.NUCOMPENS,
    FIN_COMP.VLRDESDOB AS VLRDESDOB_COMP,
    DEV.NUNOTA      AS NUNOTA_DEV,
    DEV.NUMNOTA     AS NUMNOTA_DEV,
    FIN_CRED.NUFIN  AS NUFIN_CRED,
    ABS(FIN_CRED.VLRDESDOB) AS VLRNOTA_DEV
FROM TGFFIN FIN_COMP
INNER JOIN TGFFIN FIN_CRED
    ON FIN_CRED.NUCOMPENS = FIN_COMP.NUCOMPENS
   AND FIN_COMP.VLRDESDOB = FIN_CRED.VLRDESDOB
   AND FIN_COMP.NUFIN <> FIN_CRED.NUFIN
   AND FIN_CRED.CODTIPTIT = 20
INNER JOIN TGFCAB DEV
    ON DEV.NUNOTA = FIN_CRED.NUNOTA
   AND DEV.TIPMOV = 'D'
WHERE FIN_COMP.NUNOTA = @NUNOTA_ORIG

UNION ALL

SELECT
    'Opção 2 (CODPARC+valor+data)' AS ORIGEM_OPCAO,
    FIN_COMP.NUNOTA AS NUNOTA_ORIG,
    FIN_COMP.NUFIN  AS NUFIN_COMP,
    FIN_COMP.NUCOMPENS,
    FIN_COMP.VLRDESDOB AS VLRDESDOB_COMP,
    DEV.NUNOTA      AS NUNOTA_DEV,
    DEV.NUMNOTA     AS NUMNOTA_DEV,
    FIN_CRED.NUFIN  AS NUFIN_CRED,
    ABS(FIN_CRED.VLRDESDOB) AS VLRNOTA_DEV
FROM TGFFIN FIN_COMP
INNER JOIN TGFCAB CAB_ORIG
    ON CAB_ORIG.NUNOTA = FIN_COMP.NUNOTA
   AND CAB_ORIG.TIPMOV <> 'D'
INNER JOIN TGFFIN FIN_CRED
    ON FIN_CRED.CODPARC = FIN_COMP.CODPARC
   AND FIN_CRED.CODTIPTIT = 20
   AND FIN_CRED.VLRDESDOB = FIN_COMP.VLRDESDOB
   AND ABS(DATEDIFF(DAY, FIN_COMP.DTNEG, FIN_CRED.DTNEG)) <= 120
INNER JOIN TGFCAB DEV
    ON DEV.NUNOTA = FIN_CRED.NUNOTA
   AND DEV.TIPMOV = 'D'
WHERE FIN_COMP.NUNOTA = @NUNOTA_ORIG

UNION ALL

SELECT
    'Opção 3 (valor solto)' AS ORIGEM_OPCAO,
    FIN_COMP.NUNOTA AS NUNOTA_ORIG,
    FIN_COMP.NUFIN  AS NUFIN_COMP,
    FIN_COMP.NUCOMPENS,
    FIN_COMP.VLRDESDOB AS VLRDESDOB_COMP,
    DEV.NUNOTA      AS NUNOTA_DEV,
    DEV.NUMNOTA     AS NUMNOTA_DEV,
    NULL AS NUFIN_CRED,
    ABS(FIN_COMP.VLRDESDOB) AS VLRNOTA_DEV
FROM TGFFIN FIN_COMP
INNER JOIN TGFCAB CAB_ORIG
    ON CAB_ORIG.NUNOTA = FIN_COMP.NUNOTA
   AND CAB_ORIG.TIPMOV <> 'D'
INNER JOIN TGFCAB DEV
    ON DEV.CODPARC = CAB_ORIG.CODPARC
   AND DEV.TIPMOV = 'D'
   AND DEV.VLRNOTA = ABS(FIN_COMP.VLRDESDOB)
   AND ABS(DATEDIFF(DAY, FIN_COMP.DTNEG, DEV.DTNEG)) <= 120
WHERE FIN_COMP.NUNOTA = @NUNOTA_ORIG

ORDER BY ORIGEM_OPCAO;
